/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hexabill;

import javax.swing.JOptionPane;

/**
 *
 * @author Fatmicky
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplashScreenBG = new javax.swing.JPanel();
        SplassProgressBar = new javax.swing.JProgressBar();
        SplassScreenHeading = new javax.swing.JLabel();
        LoadingTitle = new javax.swing.JLabel();
        ProgressValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        SplashScreenBG.setBackground(new java.awt.Color(102, 51, 255));
        SplashScreenBG.setPreferredSize(new java.awt.Dimension(900, 500));

        SplassScreenHeading.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        SplassScreenHeading.setForeground(new java.awt.Color(255, 255, 255));
        SplassScreenHeading.setText("HexaBill Software");

        LoadingTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        LoadingTitle.setText("Loading ...");

        ProgressValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProgressValue.setForeground(new java.awt.Color(255, 255, 255));
        ProgressValue.setText("0%");

        javax.swing.GroupLayout SplashScreenBGLayout = new javax.swing.GroupLayout(SplashScreenBG);
        SplashScreenBG.setLayout(SplashScreenBGLayout);
        SplashScreenBGLayout.setHorizontalGroup(
            SplashScreenBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashScreenBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SplassProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(SplashScreenBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoadingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProgressValue)
                .addGap(19, 19, 19))
            .addGroup(SplashScreenBGLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(SplassScreenHeading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SplashScreenBGLayout.setVerticalGroup(
            SplashScreenBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashScreenBGLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(SplassScreenHeading)
                .addGap(125, 125, 125)
                .addGroup(SplashScreenBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadingTitle)
                    .addComponent(ProgressValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SplassProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplashScreenBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplashScreenBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);  
        
        Home home = new Home();
        
        try{
            
            for (int i=0;i<=100;i++){
                Thread.sleep(i);
                sp.SplassProgressBar.setValue(i);
                sp.ProgressValue.setText(i+"%");
                
                if(i==10){
                    sp.LoadingTitle.setText("Turning on Modules...");
                }else if(i==20){
                    sp.LoadingTitle.setText("Loading Modules...");
                }else if(i==50){
                    sp.LoadingTitle.setText("Connection Successful...");
                }else if(i==80){
                    sp.LoadingTitle.setText("Launching Application...");
                }
            }
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        
        sp.setVisible(false);
        home.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingTitle;
    private javax.swing.JLabel ProgressValue;
    private javax.swing.JPanel SplashScreenBG;
    private javax.swing.JProgressBar SplassProgressBar;
    private javax.swing.JLabel SplassScreenHeading;
    // End of variables declaration//GEN-END:variables
}
